### ISSUE TITLE
Evaluation methods for LLM agents

### ISSUE THREAD

**Issue by NemoLeerink** [DmitryKutsev/agents_and_rag#2]
**How to evaluate LLM agents? Below are some ideas and concepts (with sources) that I have found.** 
_The following evaluation methods all use LLM as a judge._

---------------------------------------------------------------------------------------------------------

[Example of LLM agent evaluation using TruLens](https://github.com/truera/trulens/blob/main/trulens_eval/examples/expositional/frameworks/langchain/langchain_agents.ipynb)

Query Translation
- Evaluate that correct retrieval is occurring
- Is this query different from the previous query? Detect loops

Context Relevance
- Is retrieved context relevant to user query? 

Groundedness
- Is the response grounded in the context?

Answer Relevance
- Is the response helpful?

These questions can be answered using [Ragas](https://docs.ragas.io/en/latest/concepts/metrics/index.html#ragas-metrics) and [TruLens](https://www.trulens.org/).

[Source](https://web.stanford.edu/class/cs329t/slides/lecture_16_1.pdf)
[Source](https://www.youtube.com/watch?v=0pnEUAwoDP0)

---------------------------------------------------------------------------------------------------------

[Trajectory Evaluators](https://python.langchain.com/docs/guides/evaluation/trajectory)
- Were any actions unnecessary? (Default criteria with a score that 0-1)
- Why did the agent fail? (Custom criteria idea that can be used for improving LLM agents)
- At each step, was the right tool selected? (Custom criteria idea)
- More?

---------------------------------------------------------------------------------------------------------

**What are the task(s) that we want to test and compare on?**

Overall I think there are some interesting options to evaluate LLM agents. One point of concern is that most of them are very similar or the same to evaluating RAG systems, what we did in the last hackathon. Therefore I think it is most interesting to focus on the trajectory evaluators since that is what really separates RAG systems from LLM agents. So maybe it is an idea if we let people play with different LLM agents, provide some (trajectory) evaluations and let them write their own custom evaluations. 

Potential interesting things and tests to add:
- What kind of tests are useful from a business perspective? (Reliability)
- Does the agent achieve it's goal? (In case the goal is not QA but actually interacting with the environment)

Potential questions to ask:
- How do single agent LLM systems compare to multi agent LLM systems? Are MAS more reliable? For example, how does a single agent with 20 tools performs versus a couple of agents that each have 0-4 tools that are related and one orchestrator agent? From what I read this greatly increases reliability because roles are more clear defined and mistakes happen less often since the thinking steps agents have to take are smaller. (E.g. instead of one agent has to select the right tool out of 20 tools, it just has to select the right agent out of 5 agents).

**Comment by DmitryKutsev** [comment]
Sounds good!
And we can also add some tests manually just using concrete companies and their contact data, for instance.

**Comment by NemoLeerink** [comment]
Yes, one task could be to send an email to company X regarding subject Y for example.

**Comment by NemoLeerink** [comment]
I will close this issue as I split it into multiple smaller issues.
